name: Deploy Next.js App
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Specify a Node.js version compatible with your Next.js app

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy with rsync
        run: |
          rsync -avz --delete .next/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/nextjs-app/.next/
          rsync -avz package.json package-lock.json ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/nextjs-app/

      - name: Restart PM2 process
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ~/nextjs-app && npm install --production && pm2 restart nextjs-app || pm2 start npm --name nextjs-app -- start"
